# Generated by Django 4.2.1 on 2023-07-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_rol_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
