# Generated by Django 4.2.1 on 2023-07-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0003_product_img_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
