# Generated by Django 4.2.1 on 2023-07-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
